"""Assemble non-planet-flow metrics in registry order."""

from __future__ import annotations

from src.telemetry.metric_definition import MetricDefinition
from src.telemetry.metrics.action_decision import _ACTION_DECISION_BY_NAME
from src.telemetry.metrics.core_progress import _CORE_PROGRESS_BY_NAME
from src.telemetry.metrics.curriculum import _CURRICULUM_BY_NAME
from src.telemetry.metrics.debug import _DEBUG_BY_NAME
from src.telemetry.metrics.events import _EVENTS_BY_NAME
from src.telemetry.metrics.game_state import _GAME_STATE_BY_NAME
from src.telemetry.metrics.historical_pool import _HISTORICAL_POOL_BY_NAME
from src.telemetry.metrics.losses import _LOSSES_BY_NAME
from src.telemetry.metrics.opponent_composition import _OPPONENT_COMPOSITION_BY_NAME
from src.telemetry.metrics.timing import _TIMING_BY_NAME
from src.telemetry.metrics.trajectory_shield_debug import _TRAJECTORY_SHIELD_DEBUG_BY_NAME


def _planet_flow_metrics() -> tuple[MetricDefinition, ...]:
    from src.telemetry.planet_flow_registry import planet_flow_metric_definitions

    return planet_flow_metric_definitions()


def assemble_non_planet_flow_metrics() -> tuple[MetricDefinition, ...]:
    return (
        _CORE_PROGRESS_BY_NAME["update"],
        _CORE_PROGRESS_BY_NAME["total_env_steps"],
        _CORE_PROGRESS_BY_NAME["completed_episodes"],
        _CORE_PROGRESS_BY_NAME["samples"],
        _CORE_PROGRESS_BY_NAME["win_rate_2p"],
        _CORE_PROGRESS_BY_NAME["first_place_rate_4p"],
        _CORE_PROGRESS_BY_NAME["average_placement_4p"],
        _CORE_PROGRESS_BY_NAME["overall_win_rate"],
        _CORE_PROGRESS_BY_NAME["average_reward"],
        _CORE_PROGRESS_BY_NAME["episode_reward_mean"],
        _LOSSES_BY_NAME["policy_loss"],
        _LOSSES_BY_NAME["value_loss"],
        _LOSSES_BY_NAME["entropy"],
        _LOSSES_BY_NAME["entropy_stop"],
        _LOSSES_BY_NAME["entropy_move"],
        _LOSSES_BY_NAME["approx_kl"],
        _LOSSES_BY_NAME["approx_kl_v2"],
        _LOSSES_BY_NAME["approx_kl_first_minibatch"],
        _LOSSES_BY_NAME["approx_kl_last_minibatch"],
        _LOSSES_BY_NAME["approx_kl_v2_first_minibatch"],
        _LOSSES_BY_NAME["approx_kl_v2_last_minibatch"],
        _LOSSES_BY_NAME["log_ratio_abs_mean"],
        _LOSSES_BY_NAME["log_ratio_abs_max_last_minibatch"],
        _LOSSES_BY_NAME["importance_ratio_mean"],
        _LOSSES_BY_NAME["clip_fraction"],
        _LOSSES_BY_NAME["parity_logprob_delta_abs_mean"],
        _LOSSES_BY_NAME["parity_logprob_delta_abs_max"],
        _LOSSES_BY_NAME["parity_old_log_prob_finite"],
        _LOSSES_BY_NAME["parity_new_log_prob_finite"],
        _LOSSES_BY_NAME["total_loss"],
        _DEBUG_BY_NAME["policy_loss_2p"],
        _DEBUG_BY_NAME["value_loss_2p"],
        _DEBUG_BY_NAME["entropy_2p"],
        _DEBUG_BY_NAME["approx_kl_2p"],
        _DEBUG_BY_NAME["approx_kl_v2_2p"],
        _DEBUG_BY_NAME["total_loss_2p"],
        _DEBUG_BY_NAME["loss_sample_count_2p"],
        _DEBUG_BY_NAME["policy_loss_4p"],
        _DEBUG_BY_NAME["value_loss_4p"],
        _DEBUG_BY_NAME["entropy_4p"],
        _DEBUG_BY_NAME["approx_kl_4p"],
        _DEBUG_BY_NAME["approx_kl_v2_4p"],
        _DEBUG_BY_NAME["total_loss_4p"],
        _DEBUG_BY_NAME["loss_sample_count_4p"],
        _LOSSES_BY_NAME["minibatches"],
        _TIMING_BY_NAME["update_seconds"],
        _TIMING_BY_NAME["elapsed_seconds"],
        _TIMING_BY_NAME["rollout_seconds"],
        _TIMING_BY_NAME["ppo_seconds"],
        _TIMING_BY_NAME["env_steps_per_sec"],
        _TIMING_BY_NAME["rollout_env_steps_per_sec"],
        _TIMING_BY_NAME["samples_per_sec"],
        _TIMING_BY_NAME["ppo_samples_per_sec"],
        _DEBUG_BY_NAME["rollout_seconds_2p"],
        _DEBUG_BY_NAME["rollout_seconds_4p"],
        _DEBUG_BY_NAME["env_steps_per_sec_2p"],
        _DEBUG_BY_NAME["env_steps_per_sec_4p"],
        _DEBUG_BY_NAME["rollout_env_steps_per_sec_2p"],
        _DEBUG_BY_NAME["rollout_env_steps_per_sec_4p"],
        _DEBUG_BY_NAME["samples_per_sec_2p"],
        _DEBUG_BY_NAME["samples_per_sec_4p"],
        _DEBUG_BY_NAME["rollout_samples_per_sec_2p"],
        _DEBUG_BY_NAME["rollout_samples_per_sec_4p"],
        _DEBUG_BY_NAME["update_time_rollout_fraction"],
        _DEBUG_BY_NAME["update_time_ppo_fraction"],
        _TIMING_BY_NAME["gpu_memory_used_gb"],
        _TIMING_BY_NAME["gpu_memory_total_gb"],
        _TIMING_BY_NAME["gpu_memory_peak_gb"],
        _EVENTS_BY_NAME["gpu_name"],
        _CURRICULUM_BY_NAME["seed_scheduler_policy"],
        _CURRICULUM_BY_NAME["seed_scheduler_plateau_metric"],
        _CURRICULUM_BY_NAME["curriculum_stage_id"],
        _CURRICULUM_BY_NAME["curriculum_stage_index"],
        _CURRICULUM_BY_NAME["curriculum_stage_update"],
        _CURRICULUM_BY_NAME["curriculum_stage_dwell_updates"],
        _OPPONENT_COMPOSITION_BY_NAME["opponent_slots_total"],
        _OPPONENT_COMPOSITION_BY_NAME["opponent_slots_latest"],
        _OPPONENT_COMPOSITION_BY_NAME["opponent_slots_historical"],
        _OPPONENT_COMPOSITION_BY_NAME["opponent_slots_random"],
        _OPPONENT_COMPOSITION_BY_NAME["opponent_slots_noop"],
        _OPPONENT_COMPOSITION_BY_NAME["opponent_slots_nearest_sniper"],
        _OPPONENT_COMPOSITION_BY_NAME["opponent_slots_turtle"],
        _OPPONENT_COMPOSITION_BY_NAME["opponent_slots_opportunistic"],
        _OPPONENT_COMPOSITION_BY_NAME["opponent_historical_fallback_latest_slots"],
        _ACTION_DECISION_BY_NAME["stop_rate"],
        _ACTION_DECISION_BY_NAME["mean_active_launches_per_turn"],
        *_planet_flow_metrics(),
        _ACTION_DECISION_BY_NAME["win_rate_delta_10"],
        _ACTION_DECISION_BY_NAME["approx_kl_window_mean"],
        _ACTION_DECISION_BY_NAME["entropy_window_mean"],
        _ACTION_DECISION_BY_NAME["planet_flow_sweep_score"],
        _ACTION_DECISION_BY_NAME["stop_utilization_ratio"],
        _DEBUG_BY_NAME["mean_ships_per_launch"],
        _GAME_STATE_BY_NAME["survival_time"],
        _GAME_STATE_BY_NAME["score_share"],
        _DEBUG_BY_NAME["debug_step_mask_sum"],
        _DEBUG_BY_NAME["debug_old_log_prob_finite"],
        _DEBUG_BY_NAME["debug_returns_finite"],
        _DEBUG_BY_NAME["debug_advantages_finite"],
        _DEBUG_BY_NAME["debug_ship_bucket_mask_any_min"],
        _DEBUG_BY_NAME["debug_ship_bucket_mask_all_false"],
        _DEBUG_BY_NAME["debug_source_mask_all_false"],
        _DEBUG_BY_NAME["debug_active_launch_all_false_bucket"],
        _TRAJECTORY_SHIELD_DEBUG_BY_NAME["trajectory_shield_blocked_count"],
        _TRAJECTORY_SHIELD_DEBUG_BY_NAME["trajectory_shield_blocked_sun_count"],
        _TRAJECTORY_SHIELD_DEBUG_BY_NAME["trajectory_shield_blocked_bounds_count"],
        _TRAJECTORY_SHIELD_DEBUG_BY_NAME["trajectory_shield_blocked_unintended_hit_count"],
        _TRAJECTORY_SHIELD_DEBUG_BY_NAME["trajectory_shield_blocked_horizon_count"],
        _TRAJECTORY_SHIELD_DEBUG_BY_NAME["trajectory_shield_fallback_noop_count"],
        _TRAJECTORY_SHIELD_DEBUG_BY_NAME["trajectory_shield_legal_non_noop_rate"],
        _HISTORICAL_POOL_BY_NAME["historical_pool_size"],
        _HISTORICAL_POOL_BY_NAME["historical_pool_capacity"],
        _HISTORICAL_POOL_BY_NAME["historical_snapshot_ids"],
        _HISTORICAL_POOL_BY_NAME["historical_snapshot_ages_updates"],
        _EVENTS_BY_NAME["reseed_events"],
        _EVENTS_BY_NAME["curriculum_phase_events"],
        _EVENTS_BY_NAME["event"],
        _EVENTS_BY_NAME["checkpoint_status"],
        _EVENTS_BY_NAME["checkpoint_final"],
        _EVENTS_BY_NAME["checkpoint_reason"],
        _EVENTS_BY_NAME["checkpoint_error"],
        _EVENTS_BY_NAME["snapshot_id"],
        _EVENTS_BY_NAME["snapshot_slot"],
        _EVENTS_BY_NAME["historical_snapshot_evicted"],
        _EVENTS_BY_NAME["from_stage"],
        _EVENTS_BY_NAME["to_stage"],
        _EVENTS_BY_NAME["stage"],
        _EVENTS_BY_NAME["reason"],
        _EVENTS_BY_NAME["metric"],
        _EVENTS_BY_NAME["metric_value"],
        _EVENTS_BY_NAME["threshold"],
        _EVENTS_BY_NAME["bracket_training_phase"],
        _EVENTS_BY_NAME["weak_config"],
    )
