enabled: true
stages:
  - id: bootstrap_random_2p
    min_updates: 1000
    cooldown_updates: 0
    promote_if:
      metric: overall_win_rate
      op: ">="
      value: 0.55
      window_updates: 5
    opponent_families:
      latest: 0.0
      historical: 0.0
      random: 1.0
      noop: 0.0
      nearest_sniper: 0.0
      turtle: 0.0
      opportunistic: 0.0
    format_weights:
      2: 1.0
      4: 0.0
  - id: turtle_noop_cheese_gate_2p
    # Thought process is that if our agent doesn't learn to effectively take planets they lose, i.e. noop through whole match == tie, launching ships without taking a planet == loss, agent has to increase there prod or eliminate opponent to win
    min_updates: 2000
    cooldown_updates: 0
    promote_if:
      metric: overall_win_rate
      op: ">="
      value: 0.60
      window_updates: 5
    format_weights:
      2: 1.0
      4: 0.0
    opponent_families:
      latest: 0.0
      historical: 0.0
      random: 0.0
      noop: 0.8
      nearest_sniper: 0.0
      turtle: 0.2
      opportunistic: 0.0
  - id: mixed_exploiters_2p
    min_updates: 1000
    cooldown_updates: 10
    promote_if:
      metric: overall_win_rate
      op: ">="
      value: 0.90
      window_updates: 5
    opponent_families:
      latest: 0.0
      historical: 0.0
      random: 0.70
      noop: 0.10
      nearest_sniper: 0.07
      turtle: 0.10
      opportunistic: 0.03
    format_weights:
      2: 1.0
      4: 0.0
  # Splash in 4player
  - id: bootstrap_random_4p
    min_updates: 1000
    cooldown_updates: 0
    promote_if:
      metric: overall_win_rate
      op: ">="
      value: 0.55
      window_updates: 5
    opponent_families:
      latest: 0.0
      historical: 0.0
      random: 1.0
      noop: 0.0
      nearest_sniper: 0.0
      turtle: 0.0
      opportunistic: 0.0
    format_weights:
      2: 0.0
      4: 1.0
  - id: turtle_noop_cheese_gate_4p
    # Thought process is that if our agent doesn't learn to effectively take planets they lose, i.e. noop through whole match == tie, launching ships without taking a planet == loss, agent has to increase there prod or eliminate opponent to win
    min_updates: 2000
    cooldown_updates: 0
    promote_if:
      metric: overall_win_rate
      op: ">="
      value: 0.60
      window_updates: 5
    format_weights:
      2: 0.0
      4: 1.0
    opponent_families:
      latest: 0.0
      historical: 0.0
      random: 0.0
      noop: 0.8
      nearest_sniper: 0.0
      turtle: 0.2
      opportunistic: 0.0
  - id: mixed_exploiters_4p
    min_updates: 1000
    cooldown_updates: 10
    promote_if:
      metric: overall_win_rate
      op: ">="
      value: 0.90
      window_updates: 5
    opponent_families:
      latest: 0.0
      historical: 0.0
      random: 0.70
      noop: 0.10
      nearest_sniper: 0.07
      turtle: 0.10
      opportunistic: 0.03
    format_weights:
      2: 0.0
      4: 1.0
  # Transition to mixed 2p/4p
  - id: self_play_pressure
    min_updates: 100
    cooldown_updates: 10
    promote_if:
      metric: overall_win_rate
      op: ">="
      value: 0.90
      window_updates: 10
    opponent_families:
      latest: 0.45
      historical: 0.35
      random: 0.03
      noop: 0.02
      nearest_sniper: 0.07
      turtle: 0.04
      opportunistic: 0.04
    format_weights:
      2: 0.5
      4: 0.5
  - id: scripted_pressure
    min_updates: 100
    cooldown_updates: 10
    promote_if:
      metric: overall_win_rate
      op: ">="
      value: 0.55
      window_updates: 10
    opponent_families:
      latest: 0.2
      historical: 0.0
      random: 0.2
      noop: 0.0
      nearest_sniper: 0.4
      turtle: 0.1
      opportunistic: 0.1
    format_weights:
      2: 0.5
      4: 0.5
  - id: final_boss
    min_updates: 100
    cooldown_updates: 10
    promote_if:
      metric: overall_win_rate
      op: ">="
      value: 0.55
      window_updates: 10
    opponent_families:
      latest: 0.0
      historical: 0.0
      random: 0.0
      noop: 0.0
      nearest_sniper: 1.0
      turtle: 0.0
      opportunistic: 0.0
    format_weights:
      2: 0.5
      4: 0.5
  - id: final_boss_2
    min_updates: 100
    cooldown_updates: 10
    promote_if:
      metric: overall_win_rate
      op: ">="
      value: 0.55
      window_updates: 10
    opponent_families:
      latest: 0.0
      historical: 0.0
      random: 0.0
      noop: 0.0
      nearest_sniper: 0.0
      turtle: 0.0
      opportunistic: 1.0
    format_weights:
      2: 0.5
      4: 0.5
  - id: self_play
    min_updates: 100
    cooldown_updates: 10
    promote_if:
      metric: overall_win_rate
      op: ">="
      value: 0.60
      window_updates: 10
    opponent_families:
      latest: 0.8
      historical: 0.1
      random: 0.0
      noop: 0.0
      nearest_sniper: 0.06
      turtle: 0.02
      opportunistic: 0.02
    format_weights:
      2: 0.5
      4: 0.5
