# -- Board Constants --
BOARD_SIZE = 100.0
BOARD_CENTER = (50.0, 50.0)

# -- Planet Constants --

SUN_RADIUS = 10.0
PLANET_LAUNCH_RADIUS_OFFSET = 0.1
NO_OP_CANDIDATE_INDEX = 0

ROTATION_RADIUS_LIMIT = 50.0
MAX_OWNER_FEATURE_PLAYERS = 4

BASE_SELF_FEATURE_DIM = 30
BASE_CANDIDATE_FEATURE_DIM = 24
BASE_GLOBAL_FEATURE_DIM = 45
